# Different datatypes
#employee:
#  name: ABC
#  age: 40
#  address: XYZ
  
# This is list
#employee:
# - name: DEF
#   age: 35
#   address:TBC
# - name: GHI
#   age: 44
#   address: 
#   - old: FVD
#     new: HGF

##-- this is sample pod yaml

kind: Pod
apiVersion: v1
metadata: 
  name: test-pod
  labels: 
    env: demo
    type: frontend
spec:
  containers:
  - name: test-container
    image: hashicorp/http-echo:latest
    args: 
    - "-text=the test has been successful!"
