apiVersion: v1
kind: Pod
metadata:
  name: cmdemo1-pod
  labels:
    app.kubernetes.io/name: CmdemoApp
spec:
  containers:
  - name: cmdemoapp-container
    image: busybox:1.28
    env:
    - name: FIRSTNAME
      value: "Ajit"
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
