apiVersion: v1
kind: pod
metadata: 
 name: mymulticontapp
 labels:
   name: multicontainapp-pod
spec:
   containers: 
   - name: myapp-container
     image: busybox:1.28
     command: ['sh', '-c', 'echo the app is running && sleep 3600']
     env: 
     - name: purpose
       value: "multicontdemo"
   InitContainers:
   - name: init-myservice
     image: busybox:1.28
     command: ['sh' , '-c'] 
     args: ['until nslookup myservice.default.svc.cluster.local ; do echo waiting for service to be up; sleep 2; done']
