pipeline {
    agent any
    environment {
        GCP_PROJECT_ID = 'devops2502'
        GCP_REGION     = 'us-central1'
        IMAGE_NAME     = 'my-app'
        IMAGE_TAG      = "${env.BUILD_ID}"
        ARTIFACT_REGISTRY_URL = "${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/my-docker-repo"
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Ajit1279/GCP_Learning/tree/main/250102_DevOpsProject/AllTools.git'
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("${IMAGE_NAME}")
                    dockerImage.push("${ARTIFACT_REGISTRY_URL}/${IMAGE_NAME}:${IMAGE_TAG}")
                }
            }
        }
        
        stage('Scan with Trivy') {
            steps {
                script {
                   def scanResults = sh(script: "trivy image --exit-code 1 ${NEXUS_URL}/my-app:${IMAGE_TAG}", returnStatus: true)
                   if (scanResults != 0) {
                          error("Trivy found vulnerabilities in the image.")
                    }
                 }
             }
        }
        
        stage('Push to Nexus') {
            steps {
                script {
                    dockerImage.push("${NEXUS_URL}/my-app:${IMAGE_TAG}")
                }
            }
        }

        stage('Deploy to GKE') {
            steps {
                script {
                    sh "gcloud container clusters get-credentials my-gke-cluster --region ${GCP_REGION} --project ${GCP_PROJECT_ID}"
                    sh "kubectl apply -f k8s/deployment.yaml"
                }
            }
        }
    }
}
